spring:
  application:
    name: ticketing
  datasource:
    url: ${DB_URL:jdbc:mysql://localhost:3306/ticketing?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul&characterEncoding=UTF-8}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  sql:
    init:
      mode: always
      schema-locations: classpath:db/schema.sql
  jpa:
    hibernate:
      ddl-auto: none
    defer-datasource-initialization: false
    open-in-view: false
