DELETE FROM reservation_seat;
DELETE FROM reservation;
UPDATE seat SET status = 'EMPTY';

INSERT IGNORE INTO users (id)
SELECT ones.digit + tens.digit * 10 + 1
FROM (
    SELECT 0 AS digit
    UNION ALL SELECT 1
    UNION ALL SELECT 2
    UNION ALL SELECT 3
    UNION ALL SELECT 4
    UNION ALL SELECT 5
    UNION ALL SELECT 6
    UNION ALL SELECT 7
    UNION ALL SELECT 8
    UNION ALL SELECT 9
) AS ones
CROSS JOIN (
    SELECT 0 AS digit
    UNION ALL SELECT 1
    UNION ALL SELECT 2
    UNION ALL SELECT 3
    UNION ALL SELECT 4
    UNION ALL SELECT 5
    UNION ALL SELECT 6
    UNION ALL SELECT 7
    UNION ALL SELECT 8
    UNION ALL SELECT 9
) AS tens;
